import './styles/globals.css';
import type { Metadata } from 'next';
import { Header } from './components/Header';
import { pretendard } from './libs/font';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className={`${pretendard.className} flex justify-center`}>
          <div className="max-md:px-6 max-w-3xl w-full py-8 flex flex-col gap-8">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
