import './styles/globals.css';
import type { Metadata } from 'next';
import { Header } from './components/Header';
import { pretendard } from './libs/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} mx-auto max-w-3xl py-8 flex flex-col gap-8 text-textColor bg-backgroundColor`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
